### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by SpyMaster356** [SpyMaster356/angular2-gulp-base#1]
-  [x] add Scss support
- [x] copy images over to output
- [x] list all tools on the home page
- [ ] Improve readme
